# Generated by Django 5.0.4 on 2024-09-18 12:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                validators=[django.core.validators.MinLengthValidator(14)],
            ),
        ),
    ]
