# Generated by Django 5.0.4 on 2024-09-23 02:49

import django.core.validators
import utils.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_avatar_url_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="fiscal_identification",
            field=utils.models.NullableCharField(
                blank=True,
                max_length=18,
                null=True,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(14)],
            ),
        ),
    ]
