# Generated by Django 5.0.4 on 2024-10-02 04:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_ai",
            field=models.BooleanField(default=False),
        ),
    ]
