# Generated by Django 5.0.4 on 2024-05-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_updated_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Customer",
        ),
        migrations.DeleteModel(
            name="Mechanic",
        ),
        migrations.RemoveField(
            model_name="user",
            name="role",
        ),
        migrations.AlterField(
            model_name="user",
            name="fiscal_identification",
            field=models.CharField(blank=True, max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
