# Generated by Django 5.0.4 on 2024-06-04 01:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_fiscal_identification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="fiscal_identification",
            field=models.CharField(
                blank=True,
                max_length=18,
                null=True,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(14)],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=25,
                null=True,
                unique=True,
                validators=[django.core.validators.MinLengthValidator(14)],
            ),
        ),
    ]
