# Generated by Django 5.0.4 on 2024-09-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
        ("users", "0006_alter_user_fiscal_identification_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="services",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="services.service"
            ),
        ),
    ]
