# Generated by Django 5.0.4 on 2024-09-12 20:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("year", models.IntegerField()),
                ("mileage", models.IntegerField()),
                (
                    "transmission",
                    models.CharField(
                        blank=True,
                        choices=[("manual", "Manual"), ("automatic", "Automático")],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("gasoline", "Gasolina"),
                            ("diesel", "Diesel"),
                            ("ethanol", "Etanol"),
                            ("electric", "Elétrico"),
                            ("hybrid", "Híbrido"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("cylinder_count", models.IntegerField(blank=True, null=True)),
                ("license_plate", models.CharField(max_length=10)),
                ("chassis_number", models.CharField(max_length=17)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
