# Generated by Django 5.0.4 on 2024-09-06 02:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles", "0002_alter_vehicle_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehicle",
            options={"ordering": ["created_at"]},
        ),
        migrations.AddField(
            model_name="vehicle",
            name="cylinder_count",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="fuel_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("gasoline", "Gasolina"),
                    ("diesel", "Diesel"),
                    ("ethanol", "Etanol"),
                    ("electric", "Elétrico"),
                    ("hybrid", "Híbrido"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="transmission",
            field=models.CharField(
                blank=True,
                choices=[("manual", "Manual"), ("automatic", "Automático")],
                max_length=50,
                null=True,
            ),
        ),
    ]
