# Generated by Django 5.0.4 on 2024-09-24 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0002_alter_rating_driver"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="driver",
            field=models.ForeignKey(
                limit_choices_to=models.Q(
                    ("groups__name", "Driver"), ("is_superuser", True), _connector="OR"
                ),
                on_delete=django.db.models.deletion.CASCADE,
                related_name="given_ratings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
