# Generated by Django 5.0.4 on 2024-10-30 03:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("addresses", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="latitude",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="longitude",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
