# Generated by Django 5.0.4 on 2024-10-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_chatgroup_vehicle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="groupmessage",
            name="content",
            field=models.CharField(max_length=4096),
        ),
    ]
