# Generated by Django 5.0.4 on 2024-10-10 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_alter_groupmessage_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="mechanic_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="issue",
            name="mechanic_agreeded",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="issue",
            name="user_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="issue",
            name="user_agreeded",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="issue",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendente"),
                    ("accepted", "Aceito"),
                    ("rejected", "Rejeitado"),
                    ("in_progress", "Em andamento"),
                    ("resolved", "Resolvido"),
                ],
                max_length=50,
            ),
        ),
    ]
