# Generated by Django 5.0.4 on 2024-11-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_issue_mechanic_accepted_issue_mechanic_agreeded_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="category",
            field=models.CharField(max_length=50),
        ),
    ]
