# Generated by Django 5.0.4 on 2024-11-17 22:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0008_alter_chatgroup_options_alter_requestgroup_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="requestgroup",
            name="driver_status",
            field=models.CharField(default="pending", max_length=50),
        ),
        migrations.AlterField(
            model_name="requestgroup",
            name="mechanic_status",
            field=models.CharField(default="pending", max_length=50),
        ),
    ]
