# Generated by Django 5.0.4 on 2024-09-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("CAR", "Car"),
                            ("TRUCK", "Truck"),
                            ("MOTORCYCLE", "Motorcycle"),
                        ],
                        default="CAR",
                        max_length=20,
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
