# Generated by Django 5.0.4 on 2024-09-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Controls", "Controles"),
                            ("Harness", "Fiação"),
                            ("PTO", "PTO (Tomada de Força)"),
                            ("Maintenance", "Manutenção"),
                            ("Rotation", "Rotação"),
                            ("Outrigger", "Estabilizador"),
                            ("Body", "Carroceria"),
                            ("Electronics", "Eletrônicos"),
                            ("Resale", "Revenda"),
                            ("Hydraulics", "Hidráulica"),
                            ("Boom", "Braço"),
                            ("Test", "Teste"),
                            ("Auger", "Sonda"),
                            ("Digger", "Escavadeira"),
                            ("Chassis", "Chassi"),
                            ("Vague", "Vago"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[("Car", "Carro"), ("Motorcycle", "Moto")],
                        default="CAR",
                        max_length=20,
                    ),
                ),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
