# Generated by Django 5.0.4 on 2024-09-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="vehicle_type",
            field=models.CharField(
                choices=[("Car", "Carro"), ("Motorcycle", "Moto")],
                default="Car",
                max_length=20,
            ),
        ),
    ]
