# Generated by Django 5.0.4 on 2024-09-25 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0003_alter_category_description_alter_service_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
