name: Keep Render Alive

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  http_request_job:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP Request
        run: echo "curlhttps://example.com"