name: Keep Server Alive

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  http_request_job:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP Request
        run: |
          response=$(curl -s -w "%{http_code}" -o /dev/stdout https://mecania.vercel.app/api/keep-alive/)
          status="${response: -3}"
          body="${response%???}"
          if [ "$status" -eq 200 ]; then
            echo "$body"
          else
            echo "Request failed with status $status."
          fi
